//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITA
    {
        public int IdCita { get; set; }
        public int NumeroCitas { get; set; }
        public int IdPaciente { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Descripcion { get; set; }
        public int IdCentro { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
