//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOCUENTALABORATORIO
    {
        public int IdEstadoL { get; set; }
        public int IdLaboratorio { get; set; }
        public int IdTrabajo { get; set; }
        public int IdPaciente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int Monto { get; set; }
        public int Abono { get; set; }
        public int Faltante { get; set; }
    
        public virtual TRABAJO TRABAJO { get; set; }
        public virtual LABORATORIO LABORATORIO { get; set; }
    }
}
