//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ESTADOCUENTACENTRO
    {
        [Key]
        public int IdEstadoD { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public System.DateTime Fecha { get; set; }

        [DisplayName("Centro")]
        [Required(ErrorMessage ="No se aceptan campos vacios")]
        public int IdCentro { get; set; }


        [DisplayName("Centro")]
        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public int IdPaciente { get; set; }

        [Required(ErrorMessage ="No se aceptan campos vacios")]
        public int Monto { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public int Abono { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public int Faltante { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
