//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LABORATORIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LABORATORIO()
        {
            this.RELACIONTRALA = new HashSet<RELACIONTRALA>();
            this.ESTADOCUENTALABORATORIO = new HashSet<ESTADOCUENTALABORATORIO>();
        }
    
        [Key]
        public int IdLaboratorio { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DataType(DataType.Text)]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DataType(DataType.Date)]
        public System.DateTime Fecha { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DataType(DataType.Time)]
        public System.TimeSpan Hora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELACIONTRALA> RELACIONTRALA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTADOCUENTALABORATORIO> ESTADOCUENTALABORATORIO { get; set; }
    }
}
