//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentalDBEntities1 : DbContext
    {
        public DentalDBEntities1()
            : base("name=DentalDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CITA> CITA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<RELACIONTRALA> RELACIONTRALA { get; set; }
        public virtual DbSet<CENTRO> CENTRO { get; set; }
        public virtual DbSet<ESTADODECUENTA> ESTADODECUENTA { get; set; }
        public virtual DbSet<HistorialView> HistorialView { get; set; }
        public virtual DbSet<ESTADOCUENTALABORATORIO> ESTADOCUENTALABORATORIO { get; set; }
        public virtual DbSet<ESTADOCUENTACENTRO> ESTADOCUENTACENTRO { get; set; }
        public virtual DbSet<PACIENTE> PACIENTE { get; set; }
        public virtual DbSet<TRABAJO> TRABAJO { get; set; }
        public virtual DbSet<LABORATORIO> LABORATORIO { get; set; }
        public virtual DbSet<ESTADOTRABAJO> ESTADOTRABAJO { get; set; }
    }
}
