//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTE()
        {
            this.CITA = new HashSet<CITA>();
            this.ESTADOCUENTACENTRO = new HashSet<ESTADOCUENTACENTRO>();
            this.ESTADODECUENTA = new HashSet<ESTADODECUENTA>();
            this.TRABAJO = new HashSet<TRABAJO>();
            this.LABORATORIO = new HashSet<LABORATORIO>();
        }
    
        [Key]
        public int IdPaciente { get; set; }

        [DisplayName("Nombre del paciente")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage ="No se aceptan campos vacios")]
        public string Nombre { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public string Apellido { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public string Direccion { get; set; }

        [Required(ErrorMessage ="No se aceptan campos vacios")]
        public Nullable<long> Cedula { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public string Sexo { get; set; }

       
        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public int Edad { get; set; }

        
        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public long Telefono { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public string Estado { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public string Correo { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DisplayName("Antecedentes Patologicos")]
        public string AntecedentesPatologicos { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public string Ocupacion { get; set; }

        [DisplayName("Centro")]
        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public int IdCentro { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITA> CITA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTADOCUENTACENTRO> ESTADOCUENTACENTRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTADODECUENTA> ESTADODECUENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRABAJO> TRABAJO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LABORATORIO> LABORATORIO { get; set; }
    }
}
