//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class RELACIONTRALA
    {
        [Key]
        public int IdRelacion { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DisplayName("Trabajo")]
        public int IdTrabajo { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DisplayName("Estado")]
        public int IdEstadoT { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DataType(DataType.Date)]
        public System.DateTime Fecha { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DataType(DataType.Time)]
        public System.TimeSpan Hora { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DisplayName("Laboratorio")]
        public int IdLaboratorio { get; set; }
    
        public virtual ESTADOTRABAJO ESTADOTRABAJO { get; set; }
        public virtual TRABAJO TRABAJO { get; set; }
        public virtual LABORATORIO LABORATORIO { get; set; }
    }
}
