//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TRABAJO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRABAJO()
        {
            this.RELACIONTRALA = new HashSet<RELACIONTRALA>();
        }
    
        [Key]
        public int IdTrabajo { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DataType(DataType.Text)]
        public string Tratamiento { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public int Monto { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DisplayName("Paciente")]
        public int IdPaciente { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DataType(DataType.Date)]
        public System.DateTime Fecha { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DataType(DataType.Time)]
        public System.TimeSpan Hora { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        public int IdEstadoT { get; set; }

        [Required(ErrorMessage = "No se aceptan campos vacios")]
        [DataType(DataType.Text)]
        public string Descripcion { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RELACIONTRALA> RELACIONTRALA { get; set; }
    }
}
